### PR TITLE
Made site responsive

### PR DESCRIPTION
**Pull request by aman909909**
I have made the site responsive and created a PR. Now it works perfectly on phones as well as tablets.
I had to change the width of the generate button.
Please review the PR and let me know of any further modifications.

### CODE REVIEW

**Comment by stephin007** [comment]
image
Current Look ^^


image
Expected Look ^^


@aman909909  For Larger Devices, Can you keep the text and the dropdown in the same line as it was earlier.

**Comment by aman909909** [comment]
Is it okay if the text and the dropdown are on different lines on a mobile phone (width < 400px)?
It will on the same line for any screen >400px.
Please confirm.

**Comment by stephin007** [comment]
If you could attach a screenshot, that would be great @aman909909

**Comment by aman909909** [comment]
mid
This on larger mobile phones.

small
This on the smaller ones.

It is difficult to keep the text and the dropdown on the same line in larger phones unless we decrease the font size.

**Comment by stephin007** [comment]
> Is it okay if the text and the dropdown are on different lines on a mobile phone (width < 400px)?
It will on the same line for any screen >400px.
Please confirm.

hey @aman909909 please go ahead with this, i understood what you are saying. Keep the content on different lines if < 400 and on the same line for more than > 400

**Review by aman909909 — COMMENTED** [review]
I have made the changes. Have a look.

**Comment by stephin007** [comment]
image

the generate button becomes small when the screen size goes below 480? is this an intended change ? @aman909909 .
I  would request you to please stretch the button across the screen like when its above 480px, that fits well with the UI.
I hope that makes sense.

**Review by aman909909 — COMMENTED** [review]
Yes, I get that and have fixed it.

**Comment by stephin007** [comment]
Great, Looks good to me! 👏🏾 Merging it!

Please do star 🌟  the repository and if you want to work more, you can check other issues in this repository .

**Pull request merged**
