### PR TITLE
Justinnn07/dark mode

### PR DESCRIPTION
**Pull request by Justinnn07**
@stephin007 pls look at the color combinations!

### CODE REVIEW

**Comment by stephin007** [comment]
@Justinnn07 deployment has failed can you check if there is any unused variables?
and fix that please in this same PR.

**Comment by Justinnn07** [comment]
> @Justinnn07 deployment has failed can you check if there is any unused variables?
> and fix that please in this same PR.

done 💯

loading gif was not assigned .. 

Check that tooo

**Comment by stephin007** [comment]
there is still some same issues here @Justinnn07 
 I am in the light mode and if i refresh the screen, i should remain in the Light mode , but it switches to Dark Mode.
 
 Can you look into this please

**Comment by Justinnn07** [comment]
> there is still some same issues here @Justinnn07 
>  I am in the light mode and if i refresh the screen, i should remain in the Light mode , but it switches to Dark Mode.
>  
>  Can you look into this please
> 

Yaya ik bro .. 

I required review of colors in dark mode !

**Comment by stephin007** [comment]
Oh sure, sure @Justinnn07 
the colors look good, please move forward

**Comment by Justinnn07** [comment]
> Oh sure, sure @Justinnn07 
> the colors look good, please move forward
> 

Cool

**Comment by stephin007** [comment]
Awesome work @Justinnn07 , Merging now

**Pull request merged**
