### PR TITLE
new responsive landing page

### PR DESCRIPTION
**Pull request by goyal-Dushi**
New cover page ready, responsive, and simple.

### CODE REVIEW

**Comment by stephin007** [comment]
@goyal-Dushi looks good bro, just one final thing!

image

the text is overflowing, is this the way you designed or is this an css error?

**Comment by stephin007** [comment]
I checked, its happening between 920px to 1110px,

**Comment by goyal-Dushi** [comment]
> I checked, its happening between 920px to 1110px,
> @aman909909

Hey @stephin007, I have fixed the issue you pointed out.

**Comment by stephin007** [comment]
Great @goyal-Dushi , looking good, merging your changes!

**Review by stephin007 — APPROVED** [review]
LGTM!

**Pull request merged**
